/*
 * A bank of realistic visitor questions and where each one should land.
 * engine.test.js runs every line, so this file doubles as a regression suite.
 *
 * HOW TO ADD ONE: when you see a question the assistant got wrong, add a line:
 *     ["what the visitor typed", 'topic-id'],                 // exactly one right answer
 *     ["something ambiguous", ['topic-a', 'topic-b']],         // either is fine
 *     ["total nonsense", 'fallback'],                          // "I don't know" + forward-to-Shadab button
 *     ["vague one-word thing", ['clarify', 'topic-id']],       // "did you mean…?" buttons
 * then fix knowledge.js until `node --test chatbot/engine.test.js` is green.
 */
'use strict';

module.exports = [
  // ---- batch 1: recruiters, clients, curious visitors, chatty and messy messages -------------

 // recruiter-style
 ["Hi, I'm a recruiter at a Dubai studio. Is Shadab open to relocating?", ['location','availability']],
 ["We have an opening for a 2D animator. Would he be interested?", ['availability']],
 ["Could you share his CV please?", 'resume'],
 ["Is he currently employed?", ['job-freelance','availability']],
 ["What is his notice period?", 'terms'],
 ["Can he join immediately?", 'terms'],
 ["What's his expected salary?", 'terms'],
 ["Does he have experience in character rigging?", ['skills','three-d','experience']],
 ["Has he worked on any feature films?", ['portfolio','experience','fallback','clarify']],
 ["How many years of animation experience does he have?", 'experience'],
 ["What was his last company?", ['experience','job-freelance']],
 ["Which studios has he worked with?", 'experience'],
 ["Do you have a link to his demo reel?", 'portfolio'],
 ["Can we schedule an interview with him?", 'contact'],
 ["What's the best way to reach him?", 'contact'],
 ["Is he on LinkedIn?", 'contact'],
 ["Does he have a Behance page?", 'portfolio'],
 ["What's his highest qualification?", 'education'],
 ["Did he study animation formally?", 'education'],
 ["Which college did he graduate from?", 'education'],
 // client-style
 ["I need a 60 second explainer video. Can he do it?", ['services','skills']],
 ["I want to make a YouTube horror story channel, can he animate it?", ['services','skills']],
 ["Do you make reels for Instagram?", ['services','skills']],
 ["We need property walkthrough videos edited", ['services','availability']],
 ["How much would a 2 minute animation cost?", 'terms'],
 ["What's the turnaround for a short animation?", 'terms'],
 ["Can he work with my script and storyboard?", ['services','skills']],
 ["Is he free for a project next month?", 'availability'],
 ["How do I start a project with him?", 'availability'],
 ["Does he do revisions?", 'terms'],
 ["Can he do cartoon animation for kids?", ['services','skills']],
 ["do you do logo animation", ['skills','services']],
 ["Can he make an animated explainer for our app?", ['services','skills']],
 // curious-visitor style
 ["So what does Shadab do exactly?", 'about'],
 ["Tell me something about him", ['about']],
 ["Who's the person behind this portfolio?", ['about','identity']],
 ["Is this website made by him?", ['about','identity','fallback','clarify']],
 ["What's his story?", ['about','experience','fallback','clarify']],
 ["How good is he?", ['strengths','skills','fallback','clarify']],
 ["What's he best at?", 'skills'],
 ["What are his main strengths?", 'strengths'],
 ["Which software is he best at?", ['software','skills']],
 ["Does he use Adobe products?", 'software'],
 ["Can he use Blender?", 'software'],
 ["Is he an Adobe Animate expert?", 'software'],
 ["How does he approach a new project?", ['strengths']],
 ["Do you animate frame by frame?", 'skills'],
 ["What type of animation does he do?", ['skills','services','about']],
 ["Does he do 2D or 3D?", ['three-d','skills']],
 ["Where is he from?", 'location'],
 ["Is he in Dubai right now?", ['location','job-freelance']],
 ["What time zone is he in?", 'location'],
 ["Does he speak Arabic?", 'languages'],
 ["How old is he?", 'personal'],
 ["What's his phone number?", 'contact'],
 ["Can I WhatsApp him?", 'contact'],
 ["What's his Instagram handle?", 'contact'],
 ["Does he have a YouTube channel?", 'portfolio'],
 ["Show me some of his animations", 'portfolio'],
 ["Any recent projects?", ['portfolio','fallback','clarify']],
 ["What has he made for clients?", ['portfolio','services','experience']],
 // chatty / messy
 ["hey! quick question", ['greeting','help','fallback','clarify']],
 ["hello, are you there?", ['greeting','identity']],
 ["lol ok", ['affirm','fallback']],
 ["thank u!", 'thanks'],
 ["ok thanks bye", ['bye','thanks']],
 ["wow nice work", ['affirm','portfolio','fallback']],
 ["idk what to ask", 'help'],
 ["what can i ask u", 'help'],
 ["r u a bot", 'identity'],
 ["r u real", 'identity'],
 ["r u shadab", 'identity'],
 ["are you chat gpt", ['identity']],
 ["is this automated", 'identity'],
 ["who programmed this", 'identity'],
 // typos / sloppy
 ["whats his emial", 'contact'],
 ["wher is he basd", ['location','fallback','clarify']],
 ["hiw much experince", 'experience'],
 ["can i see his portfollio", 'portfolio'],
 ["skilz?", ['skills','fallback','clarify']],
 ["availble for hire?", 'availability'],
 ["contatc info", 'contact'],
 ["wat softwares he knw", 'software'],
 ["linkedn profile", 'contact'],
 ["cv pls", 'resume'],
 // off topic / out of scope
 ["What's the weather in Mumbai?", 'offtopic'],
 ["Tell me a joke", 'offtopic'],
 ["Who is the president of India?", 'offtopic'],
 ["Can you help me with my homework?", ['offtopic','help']],
 ["What's 2+2?", ['fallback','offtopic']],
 ["Does he like pizza?", ['fallback','personal']],
 ["Is he single?", 'personal'],
 ["Does he have a girlfriend?", 'personal'],
 ["What's his religion?", 'personal'],
 ["What's the meaning of life?", 'fallback'],
 ["Do you take payments via PayPal?", ['terms','fallback','clarify']],
 ["Can he teach animation?", ['fallback','clarify','skills','about']],
 ["Does he offer courses or tutorials?", ['fallback','clarify','services']],
 ["Does he do voice acting?", 'skills'],
 ["Is he good with After Effects templates?", 'software'],
 ["Does he use AI tools?", ['software','fallback','clarify']],
 ["What's his availability in October?", 'availability'],
 ["Will he work for equity?", ['fallback','clarify','terms']],
 ["Can he work night shifts?", ['fallback','clarify','remote','availability']],
 ["Does he have a team?", ['fallback','clarify','strengths']],
 ["Is he a freelancer or full-time?", ['availability','job-freelance']],
 ["Would he relocate to Saudi Arabia?", ['location','availability']],
 ["Does he need a visa to work in the UAE?", 'terms'],

  // ---- batch 2: statements instead of questions, screening questions, fragments, multi-part --

 // statements / intents rather than questions
 ["I want to hire a 2D animator for my YouTube channel", ['availability','services']],
 ["Looking for a freelance video editor", ['availability']],
 ["We are hiring animators in Dubai", ['availability','location']],
 ["Need someone to animate my story", ['services','availability']],
 ["I'd like to see his previous work", 'portfolio'],
 ["I would like to talk to Shadab", 'contact'],
 ["Please share his contact", 'contact'],
 ["Kindly send resume", 'resume'],
 ["pls tell me abt his work", ['portfolio','experience','about']],
 ["Sir, what are his skills?", 'skills'],
 ["Do the needful and send his portfolio link", 'portfolio'],
 ["I saw your work on Behance, it's great", ['portfolio','affirm','thanks','fallback']],
 ["Your portfolio is amazing", ['portfolio','affirm','fallback']],
 // screening questions
 ["What is your current CTC?", 'terms'],
 ["What is your expected CTC", 'terms'],
 ["Are you comfortable relocating?", 'location'],
 ["Are you willing to relocate to UAE?", 'location'],
 ["Do you have a valid passport?", ['terms','fallback','clarify','personal']],
 ["How soon can you join?", 'terms'],
 ["What is your highest education?", 'education'],
 ["Which year did you graduate?", 'education'],
 ["Are you currently working?", ['job-freelance','availability']],
 ["What was your last role?", ['experience','job-freelance']],
 ["Why did you leave your last job?", 'unknown'],
 ["Do you have experience in real estate videos?", ['services','experience']],
 ["Have you worked with YouTube creators?", ['experience','services','skills','portfolio']],
 ["Do you have experience with character animation?", ['skills','experience']],
 ["Do you know Adobe After Effects and Premiere Pro?", 'software'],
 ["Are you proficient in Illustrator?", 'software'],
 ["What version of After Effects do you use?", ['software']],
 ["Do you use Mac or PC?", ['fallback','clarify','software']],
 ["Do you work with a team or alone?", ['fallback','clarify','strengths','job-freelance']],
 ["How many projects have you completed?", ['experience','portfolio','fallback','clarify']],
 ["What industries has he worked in?", ['experience','services','fallback','clarify']],
 ["What is his strongest skill?", ['skills','strengths']],
 ["What is his greatest achievement?", 'unknown'],
 ["Any awards or certifications?", 'unknown'],
 // one-word / fragments
 ["rate", 'terms'],
 ["cost", 'terms'],
 ["pricing?", 'terms'],
 ["degree", 'education'],
 ["resume", 'resume'],
 ["hire", 'availability'],
 ["email", 'contact'],
 ["linkedin", 'contact'],
 ["youtube", ['portfolio','services','clarify']],
 ["behance", 'portfolio'],
 ["location", 'location'],
 ["tools", 'software'],
 ["skills", 'skills'],
 ["experience", 'experience'],
 ["contact me", ['contact']],
 ["hello there", 'greeting'],
 ["yo", 'greeting'],
 ["sup", 'howareyou'],
 ["menu", 'help'],
 ["options", 'help'],
 ["hobbies", 'personal'],
 ["weather", 'offtopic'],
 ["asdf", 'fallback'],
 // messy / multi-sentence
 ["Hi there! I'm Priya from Pixel Studio. We're looking for a character animator. Can you tell me if Shadab is available and how to reach him?", ['availability','contact']],
 ["hey, i found ur website. can u tell me more about what u do", ['about']],
 ["good afternoon. could you please tell me what software he is familiar with?", 'software'],
 ["Hello! Quick one - is he open to full-time roles or only freelance?", ['availability']],
 ["hi, who is this?", ['identity','about']],
 ["Is he a good fit for a horror animation series?", ['services','skills','strengths','portfolio']],
 ["Can you show me an example of his character design?", ['portfolio','skills']],
 ["Where can I find his work on YouTube?", 'portfolio'],
 ["do u have insta", ['contact']],
 ["whats ur number", 'contact'],
 ["ur email id pls", 'contact'],
 ["how can i get in contact with him", 'contact'],
 ["is he available on whatsapp", ['contact','availability']],
 ["can i call him", 'contact'],
 ["does he answer emails quickly", ['fallback','clarify','contact','terms']],
 ["how quickly does he reply", ['fallback','clarify','terms','contact']],
 // skills detail
 ["does he do storyboards", 'skills'],
 ["can he do lip sync", 'skills'],
 ["does he know rigging", ['three-d','skills']],
 ["is he good at character design", 'skills'],
 ["does he do backgrounds and layouts", 'skills'],
 ["can he do color grading", 'skills'],
 ["does he do sound effects", 'skills'],
 ["can he do subtitles", ['fallback','clarify','skills']],
 ["does he do thumbnails", ['fallback','clarify','skills','services']],
 ["can he make animated logos", ['skills','services']],
 ["does he do whiteboard animation", ['skills','fallback','clarify','services']],
 ["does he do anime style", ['skills','fallback','clarify']],
 // honest-unknown
 ["how many followers does he have", 'unknown'],
 ["what's his best project", ['portfolio','fallback','clarify']],
 ["does he have any clients from the US", ['experience','fallback','clarify']],
 ["is he fluent in french", 'languages'],
 ["can he speak arabic", 'languages'],
 ["what's his mother tongue", 'languages'],
 ["what's his nationality", 'location'],
 ["is he indian", ['location','fallback','clarify']],
 ["what's his address", 'location'],
 ["where's his office", ['location','fallback','clarify']],
 ["does he have a company", ['fallback','clarify','job-freelance','availability']],
 ["is he a student", ['education','fallback','clarify','experience']],
 ["how tall is he", 'fallback'],
 ["what's his favourite cartoon", ['personal','fallback']],
 ["tell me about his family", 'personal']
];
